version: "3.8"
services:
        mysql:
                image: mysql:latest
                container_name: mysql
                networks: 
                   - mynetwork
                volumes:
                        - /home/huuquan/mysql-sever:/etc/mysql/conf.d
                restart: always 
                environment:
                   MYSQL_ROOT_PASSWORD: Luonghuuquan1!
                   MYSQL_DATABASE: elgg
                   MYSQL_USER: quanluong
                   MYSQL_PASSWORD: Luonghuuquan1!
        elgg: 
                depends_on: 
                     - mysql
                container_name: elgg
                build:
                        dockerfile: elggbuild
                        context: .
                restart: always
                networks:
                        - mynetwork
                volumes:
                        - /home/huuquan/elgg_backup:/home/backup
                ports: 
                        - "8000:80"
                environment:
                        WORDPRESS_DB_HOST: mysql:3306
                        WORDPRESS_DB_USER: quanluong
                        WORDPRESS_DB_PASSWORD: Luonghuuquan1!
                        WORDPRESS_DB_NAME: elgg
networks:
        mynetwork:
                driver: bridge
